name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Restore Cargo cache
        id: restore-cargo
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Create Solana keypair
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase -o ~/.config/solana/id.json

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install surfpool
        run: curl -sL https://run.surfpool.run/ | bash

      - name: Install Just
        run: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin

      - name: Restore pnpm cache
        id: restore-pnpm
        uses: actions/cache/restore@v4
        with:
          path: |
            clients/typescript/node_modules
            ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: just setup

      - name: Check formatting
        run: just fmt-check

      - name: Check Linting
        run: just lint-check

      - name: Build program
        run: just build-program

      - name: Build client
        run: just build-client

      - name: Test program
        run: just test-program

      - name: Test client
        run: just test-client

      - name: Save Cargo cache
        uses: actions/cache/save@v4
        if: always() && steps.restore-cargo.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

      - name: Save pnpm cache
        uses: actions/cache/save@v4
        if: always() && steps.restore-pnpm.outputs.cache-hit != 'true'
        with:
          path: |
            clients/typescript/node_modules
            ~/.local/share/pnpm/store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Kill surfpool validator
        if: always()
        run: just kill-validator
